// Vuetify elements with icon Props
export const iconMaps: { [component: string]: string[] } = {
  "v-alert": ["icon"],
  "v-autocomplete": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-badge": ["icon"],
  "v-banner": ["icon", "icon-color"],
  "v-btn": ["icon"],
  "v-carousel": ["delimiter-icon", "next-icon", "prev-icon"],
  "v-checkbox": [
    "append-icon",
    "indeterminate-icon",
    "off-icon",
    "on-icon",
    "prepend-icon",
  ],
  "v-simple-checkbox": ["indeterminate-icon", "off-icon", "on-icon"],
  "v-chip": ["close-icon", "filter-icon"],
  "v-chip-group": ["next-icon", "prev-icon"],
  "v-combobox": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-data-footer": ["first-icon", "last-icon", "next-icon", "prev-icon"],
  "v-data-table": ["expand-icon"],
  "v-date-picker": ["next-icon", "prev-icon", "year-icon"],
  "v-date-picker-title": ["year-icon"],
  "v-date-picker-header": ["next-icon", "prev-icon"],
  "v-expansion-panel-header": ["disable-icon-rotate", "expand-icon"],
  "v-file-input": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-input": ["append-icon", "prepend-icon"],
  "v-list-group": ["append-icon", "prepend-icon"],
  "v-overflow-btn": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-pagination": ["next-icon", "prev-icon"],
  "v-radio-group": ["append-icon", "prepend-icon"],
  "v-radio": ["off-icon", "on-icon"],
  "v-range-slider": ["append-icon", "prepend-icon"],
  "v-rating": ["empty-icon", "full-icon", "half-icon"],
  "v-select": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-slider": ["append-icon", "prepend-icon"],
  "v-slide-group": ["next-icon", "prev-icon"],
  "v-stepper-step": ["complete-icon", "edit-icon", "error-icon"],
  "v-switch": ["append-icon", "prepend-icon"],
  "v-tabs": ["icons-and-text", "next-icon", "prev-icon"],
  "v-tabs-items": ["next-icon", "prev-icon"],
  "v-textarea": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-text-field": [
    "append-icon",
    "append-outer-icon",
    "clear-icon",
    "prepend-icon",
    "prepend-inner-icon",
  ],
  "v-timeline-item": ["icon", "icon-color"],
  "v-treeview": [
    "expand-icon",
    "indeterminate-icon",
    "loading-icon",
    "off-icon",
    "on-icon",
  ],
  "v-treeview-node": [
    "expand-icon",
    "indeterminate-icon",
    "loading-icon",
    "off-icon",
    "on-icon",
  ],
  "v-window": ["next-icon", "prev-icon"],
};
